### ISSUE TITLE
Is there a way to modify the corder radius of sent images

### ISSUE THREAD

**Issue by Jnss98b** [CapnKitten/Material-Discord#100]
I tried modifying border-radius, border-radius-big, and border-radius-bar but none of them changed that

![image](https://user-images.githubusercontent.com/24306400/85616336-85088b00-b62b-11ea-8297-1513728f1419.png)

**Comment by CapnKitten** [comment]
Since v2.3, the messages bubble, preview images, and embedded attachments are handled by `--new-messages-radius`. If you wish to only change the radius of the images, you can do by adding this to the custom CSS:
```css
.imageWrapper-2p5ogY {
	border-radius: RADIUS !important;
}
```
