### ISSUE TITLE
Request: option to disable animated server voice chat/stream icons

### ISSUE THREAD

**Issue by rwxr-xr-xis** [CapnKitten/Material-Discord#120]
I find them very distracting and have a hard time focusing when they're there, I think an option for disabling them would be nice

**Comment by CapnKitten** [comment]
You can't have options with normal CSS, but you can add this to the custom CSS tab in your user settings:
```css
.iconBadge-2NuvG9 {
	animation: none !important;
}
```
