### ISSUE TITLE
Add support for compact mode

### ISSUE THREAD

**Issue by zisis912** [CapnKitten/Material-Discord#143]
When I installed the theme, it looked weird and I knew why. It is because I have compact mode. Could you please make it work on compact mode? I hate cozy mode

**Comment by CapnKitten** [comment]
The theme already has support for compact mode.
![a75H3c](https://user-images.githubusercontent.com/4013216/115130615-17b15680-9fbf-11eb-95ca-b495999c141f.png)

**Comment by zisis912** [comment]
![image](https://user-images.githubusercontent.com/65046191/115145996-50a00880-a05d-11eb-9551-66a15f0b2860.png)
not for me, it seems like the complete timestamps plugin breaks it

**Comment by CapnKitten** [comment]
There's no clear way from what I can see to differentiate between the plugin being off and on. So as a quick fix for the time being, you can add the following code to either your custom css or the theme file itself:
```css
.wrapper-2a6GCs.compact-T3H92H {
	margin-left: 136px;
}

.wrapper-2a6GCs.compact-T3H92H .contents-2mQqc9 {
	margin-left: -156px;
	padding-left: 156px;
	text-indent: calc(-156px - -1rem);
}
```
