### ISSUE TITLE
background image?

### ISSUE THREAD

**Issue by allaze-eroler** [CapnKitten/Material-Discord#149]
Hello, I've like to have the same possibility than your translucence theme: https://github.com/CapnKitten/Translucence

So, is there a way to customize your material theme?

**Comment by CapnKitten** [comment]
There is, you just have to play around with the variables listed [here](https://github.com/CapnKitten/Material-Discord#variables). A quick example would be like:
```css
:root {
    --app-bg: url(https://i.imgur.com/U8bSjj5.jpg);
}

.theme-dark {
	--main-color: transparent;
	--main-alt: transparent;
	--server-color: transparent;
	--chat-color: transparent;
}
```

**Comment by allaze-eroler** [comment]
thank you very much! that is what i needed!

**Comment by allaze-eroler** [comment]
Sorry to bother you again, i just realize that i need to make the bubble text translucent too with a good blur from your translucent theme... what is the best method?

**Comment by CapnKitten** [comment]
That's the tricky part. For the message bubbles to have a radius and to group messages that are said by the same person, there's some overlap that would look bad if it were to be translucent.

**Comment by allaze-eroler** [comment]
That is what i noticed when studying in your code source...

**Comment by allaze-eroler** [comment]
so far, this is what i managed to get with a custom css:
![Discord_kc591RYz3a](https://user-images.githubusercontent.com/6775478/123779045-0bf0e300-d8d2-11eb-86e3-a306adbca208.png)

only the problem is that i have no idea how to blur the box background... like your translucence theme.

**Comment by CapnKitten** [comment]
If you're referring to the background that includes `--app-bg`, add this:
```css
.bg-h5JY_x {
    filter: blur(var(--app-blur));
}
```
