### ISSUE TITLE
[SUGGESTION] Channel/Role Header Capitilization

### ISSUE THREAD

**Issue by BLANK-TH** [CapnKitten/Material-Discord#155]
A toggle to allow people to be able to choose whether channel categories and role categories are capitalized would be useful, since some servers have their category titles written inconsistently and it drives me crazy.

**Comment by CapnKitten** [comment]
Having toggles in css is not possible. What can be done is giving you a tiny bit of code to put in your custom css to revert it to being capitalized.
```css
.sidebar-2K8pFh .container-2ax-kl,
.members-1998pB .container-2ax-kl {
    font-size: 12px;
    text-transform: uppercase;
}
```
