### ISSUE TITLE
Can I change fonts?

### ISSUE THREAD

**Issue by Tomocie** [CapnKitten/Material-Discord#167]
nice theme i love this
i'm japanese user, and css beginner.
i want to change fonts
to add this,
```css
	--font-primary: "Noto Sans JP Black";
  	--font-display: "Noto Sans JP Black ";
  	--font-code: "Source Code Pro";
  	--font-japanese: "Noto Sans JP";
 ```
 but it's not works
 what should I do?

**Comment by CapnKitten** [comment]
This should work for you.
```css
:root {
  --app-font: "Noto Sans JP";
  --code-font: "Source Code Pro";
}
```
