### ISSUE TITLE
AMOLED theme variant

### ISSUE THREAD

**Issue by seriaati** [CapnKitten/Material-Discord#176]
I Would like to have an AMOLED version for this theme!
I know you can customize the colors with some CSS, but I'm not just not really good at colors 😂
And maybe there are some material design guidelines regarding AMOLED themes, I'm not sure
Anyways, I love this theme, thank you for making it!

**Comment by CapnKitten** [comment]
An AMOLED version would just make everything black or near black. I can give you the code to make it look like that without touching the theme.

**Comment by seriaati** [comment]
sure that sounds good to me, thanks!

**Comment by CapnKitten** [comment]
Paste this in your custom css.
```css
.theme-dark {
    --main-color: #090909;
    --main-alt: #000;

    --sidebar-panel-color: #0f0f0f;
    --status-picker-color: #141414;

    --chat-color: #000;
    --main-textarea-color: #000;
    --main-textarea-border: #333;
    --main-textarea-color-alt: #222;

    --message-color: #0b0b0b;
    --message-color-hover: #111;
    --attachment-color: rgba(0,0,0,0.75);

    --popout-color: #111;
    --popout-color-alt: #000;
    --emoji-category-header: rgba(17,17,17,0.95);
}
```
