### ISSUE TITLE
Add an option to disable MacOS styled window titlebar buttons

### ISSUE THREAD

**Issue by coinkillerl** [CapnKitten/Material-Discord#188]
Add an option to restore the stock discord window titlebar buttons.
![image](https://user-images.githubusercontent.com/30773734/230950910-13c791d2-ef13-41b0-a6b6-491012ff41ee.png)
to this
![image](https://user-images.githubusercontent.com/30773734/230950830-cc344561-6123-4ed1-b2a4-38a912250e8f.png)

**Comment by CapnKitten** [comment]
There's no way to have options with css; you have to override it. Use the code below to do that.
```css
.typeWindows-2-g3UY .winButton-3UMjdg:before, .typeWindows-2-g3UY .winButton-3UMjdg:after {
  display: none;
}
.typeWindows-2-g3UY .winButton-3UMjdg svg {
  display: unset;
}
.typeWindows-2-g3UY .winButtonMinMax-3RsPUg:hover {
  background-color: var(--background-modifier-hover);
}
.typeWindows-2-g3UY .winButtonClose-3Q8ZH5:hover {
  background-color: var(--status-danger);
}
```
