### ISSUE TITLE
Please add text color options

### ISSUE THREAD

**Issue by randomhuman9** [CapnKitten/Material-Discord#197]
The default color for text seems to be a very bright shade of white. So the contrast with the dark backgrounds is very high. These options can help people who would prefer a lower contrast.
![image](https://github.com/CapnKitten/Material-Discord/assets/65187211/7d3d3e7a-71ba-411f-81a7-c041d17d95cf)

**Comment by CapnKitten** [comment]
Discord already has text color variables you can change, and that's what the theme uses.

```css
.theme-dark {
    --text-normal: hsl(210, 9.1%, 87.1%);
    --text-muted: hsl(214, 8.1%, 61.2%);

    --interactive-normal: hsl(215, 8.8%, 73.3%);
    --interactive-hover: hsl(210, 9.1%, 87.1%);
    --interactive-active: hsl(0, 0%, 100%);
    --interactive-muted: hsl(228, 6%, 32.5%);
}
```
