### ISSUE TITLE
Color issues with Material You enabled

### ISSUE THREAD

**Issue by s1nnohlakes** [CapnKitten/Material-Discord#204]
I'm not sure if this change was intentional or not, but recently, I've noticed that texts and other elements are kind of hard to read when I'm using the `Material You` addon. The text and other elements used to be much more white-ish than the background, but recently it has sort of blended i, making it harder to read/notice. And yes, I am aware I'm using a gray palette for this, but it didn't affect anything before.

Screenshots:
| Before  | After |
| ------------- | ------------- |
| ![image](https://github.com/CapnKitten/Material-Discord/assets/51394649/7afc52c5-77db-407a-bb3d-4883cfda1987) | ![Screenshot_155](https://github.com/CapnKitten/Material-Discord/assets/51394649/7208d303-6243-41f8-9545-8a08ab06d4b0) |
| ![Screenshot_156](https://github.com/CapnKitten/Material-Discord/assets/51394649/c9fb6551-4207-4e69-a419-516bb4c80603) | ![Screenshot_157](https://github.com/CapnKitten/Material-Discord/assets/51394649/06055039-5a43-49e5-b50c-5259a346df9d) |

**Comment by CapnKitten** [comment]
I changed the text variables to have a shade of the accent color in Material You, but since this is all just CSS, there's no way to check for how light or dark one's accent color is. The code below will revert the text color changes until I get it more dialed in. Placing it in the theme anywhere below the Material You import should work.
```css
.theme-dark {
    --menu-item-text-color: hsl(0,0%,76%);

    --card-header-text-color: hsl(0,0%,93%);

    --channels-default: var(--primary-360);
    --channel-icon: var(--primary-400);
    --interactive-active: var(--white-500);
    --interactive-normal: var(--primary-330);
    --interactive-muted: var(--primary-500);

    --header-primary: var(--primary-130);
    --header-secondary: hsl(0,0%,92%);

    --text-normal: var(--primary-230);
    --text-muted: var(--primary-360);
}
```

**Comment by CapnKitten** [comment]
Scratch that, restart your Discord to get an update I just pushed and use the following code to adjust the text lightness. A higher number will result in a brighter text color, and vice versa.
```css
.theme-dark {
    --text-lightness-modifier: 1.0;
}
```
