### ISSUE TITLE
Suggestion: add a catppuccin version

### ISSUE THREAD

**Issue by bl4xe** [CapnKitten/Material-Discord#209]
I really love this theme and have been using it for over a year now but I also really love the catppuccin mocha color palette and would loove to see a combination of the both as the official catppuccin discord theme really sucks apart from the colors. I have never coded anything with CSS before and I know nothing about code in general so if it's not too much to ask I would love to see a different version / maybe an addon?

**Comment by Wildtick** [comment]
I would like that too

**Comment by CapnKitten** [comment]
There are variables in place that allow you to customize the entire color scheme. They are listed on the readme <https://github.com/CapnKitten/Material-Discord#variables>.

Dark theme example:
```css
.theme-dark {
  --main-color: hsl(0,0%,10%);
}
```

Light theme example:
```css
.theme-light {
  --main-color: hsl(0,0%,96%);
}
```
