### ISSUE TITLE
Is there a var I can modify to change the discord icon color?

### ISSUE THREAD

**Issue by LuminarySage** [CapnKitten/Material-Discord#211]
The same color is also used for the folder icon, the background for the add server and discovery buttons, and the server icon background color for servers using the default initialism icon

**Comment by CapnKitten** [comment]
```css
.wrapper_f90abb .childWrapper_f90abb,
.wrapper_f90abb:hover .childWrapper_f90abb,
.circleIconButton_db6521,
.circleIconButton_db6521.selected_db6521,
.folderIconWrapper_bc7085[style="background-color: rgba(88, 101, 242, 0.4);"],
.expandedFolderIconWrapper_bc7085 svg[style="color: rgb(88, 101, 242);"] {
    --accent-hsl: 0,0%,100%;
    --accent-hsl--material-you: var(--accent-hsl);
    --accent-text-color--material-you: hsl(0,0%,0%);
}
```
