### ISSUE TITLE
Broken bar above friend list

### ISSUE THREAD

**Issue by nnra6864** [CapnKitten/Material-Discord#233]
Self explanatory, here's [my config](https://github.com/nnra6864/Ricerland/blob/Arch/vesktop/settings/quickCss.css) and a screenshot:
![Image](https://github.com/user-attachments/assets/38033f43-125b-4d20-a7e2-c598f17377a0)

**Comment by CapnKitten** [comment]
I wouldn't consider it broken. You're using a transparent hex code, and that specific header uses the `.themed__9293f` class alongside it which adds a color to it. Just make it transparent with the code below.

```css
.container__9293f.themed__9293f {
    background-color: transparent;
}
```

**Comment by nnra6864** [comment]
Thanks for the quick response, it worked!
However, there's still a small shadow to the right of it.
![Image](https://github.com/user-attachments/assets/71d2bb7e-d9db-472d-a780-ff5594ec0a72)

I didn't manage to fix it so I'm assuming it's possibly the element next to it:
```css
/* Fixes the bar above friend list */
.container__9293f.themed__9293f {
	background-color: transparent;
	box-shadow: 0;
}
```

**Comment by CapnKitten** [comment]
This'll get rid of it.

```css
.children__9293f:after {
    display: none;
}
```
