### ISSUE TITLE
Assistance with customization and some suggestions.

### ISSUE THREAD

**Issue by AerinUWU** [CapnKitten/Material-Discord#235]
Hello,
First, I would to thank you for this awesome theme I've been enjoying it a lot, ever since recently where a theme I used for years got neglected and broken completely.

So, I'm trying to customize the color scheme to my liking however, couldn't figure out how to change the color of the share screen button, including the other ones would appreciate some navigation on how to change it.
![Image](https://github.com/user-attachments/assets/dabafffd-e8dc-4b26-84bb-2aa4933e612e)
Also forgot to ask is it possible to change the color of this, because it ever so slightly has a small tint of blue and I would like it to be monochrome.
![Image](https://github.com/user-attachments/assets/1a962733-f466-42bd-8464-26811b2e3358)
You can also see that there is a big difference in the width compared to the two pictures, because one got early access to the new UI.

Another thing I was wondering if it is possible to customize the width of the sidebar, since it's so narrow it's hard read channels names, etc.
![Image](https://github.com/user-attachments/assets/19a197d3-f92b-4a2a-a0a9-d289a16de3be)

I have one suggestion to ask, I personally use the horizontal servers code, (@import url('https://discordstyles.github.io/HorizontalServerList/dist/HorizontalServerList.css');) that I found from this website, (https://bdeditor.dev/themes) and I think that having the settings, plus the account settings like, changing status, DND, away or switching accounts, could be in the top right corner, and it'll have more space on the bottom left to have the important buttons, at least it makes more sense from UX standpoint for me.
Here is a picture for reference: (full transparency that is the theme I used, and I just really like this layout.)
![Image](https://github.com/user-attachments/assets/3067bae8-d37e-4ad7-b15c-1ff1e9beb12d)

Lastly, you can see that with the new UI and horizontal servers it's quite broken, just wanted to share this in case you plan on integrating your own horizontal servers or something alike.
![Image](https://github.com/user-attachments/assets/05b55345-2b40-438e-b8c4-6df75c077894)

Thank you very much for your work and have a nice day!

**Comment by CapnKitten** [comment]
1. Use this code to manually change those specific buttons.
```css
.container_e131a9 .lookFilled__201d5 {
  --button-background: hsl(0,0%,0%);
  --button-text-color: hsl(0,0%,100%);
}
```
2. Variables are listed on this repo's [readme](https://github.com/CapnKitten/Material-Discord). This specific variable is `--status-picker-color`.
3. The width of the channels list is whatever Discord set it to, but can be changed with the code below.
```css
html:not(.visual-refresh) .sidebar_c48ade:not(.hidden_c48ade) {
  width: 300px !important;
}
```
4. [Spotify Discord](https://github.com/CapnKitten/Spotify-Discord) had a similar thing with the user status area in the top right corner, but that caused some issues that I didn't feel like fixing. So no plans to add it to MD, sorry.
5. No plans to add a separate horizontal server list to the theme since that specific theme works fine with current version of Discord. Some themes, like all of my themes, support the refresh, but most do not yet since it's not out for everyone yet.

**Comment by AerinUWU** [comment]
Thank you very much for assisting me, and please don't apologize for having no plans, it's your theme and it's totally understandable!

About the variables, I did read them and tried a lot of them it's just kinda hard for me as a visual person to see what changes what, cause I'm not a code person I just inserted a lot of variables, and played with it until I got my desirable results, it seems like I missed the status picker color one.

Final two things, the width code worked like a charm however in the DM area, the hover highlight, selected DM and the X to close the DM, don't stretch until the edge of the sidebar.
![Image](https://github.com/user-attachments/assets/71b42321-7809-4e22-a32e-a2e45137be8a)
And I was wondering if there is an option to change the color of links and tagged messages without changing the accent color?
![Image](https://github.com/user-attachments/assets/8ef3fdec-0a9c-44ec-8579-3d677c8fc301)
![Image](https://github.com/user-attachments/assets/21a8bdff-ec38-4c2d-888c-3f7a4e83b041)


Once again big thanks for your help and your time, have a nice day or night!

**Comment by CapnKitten** [comment]
```css
/* sidebar settings - adjust the 300px and leave the rest */
html:not(.visual-refresh) .sidebar_c48ade:not(.hidden_c48ade) {
    --sidebar-width: 300px;

    width: var(--sidebar-width) !important;
}

.bannerImage_f37cb1 {
    width: var(--sidebar-width);
}

.bannerImg_f37cb1 {
    width: inherit;
}

.channel__972a0 {
    max-width: calc(var(--sidebar-width) - 16px);
}

/* mention settings */
.mentioned__5126c .messageContent_c19a55 {
  background-color: hsla(0, 0%, 0%, 0.3);
}

.theme-dark .wrapper_f61d60 {
  color: hsl(0, 0%, 0%);
}
```
