### ISSUE TITLE
Broken chat and server list

### ISSUE THREAD

**Issue by nnra6864** [CapnKitten/Material-Discord#245]
I am assuming this has to do something with me using custom css:

![Image](https://github.com/user-attachments/assets/129f6b6a-9f00-48a9-9a91-f90d26f8714d)

```css
/* Ricer by nnra */
/* https://github.com/CapnKitten/Material-Discord */

:root {
	/* Variables */
	--background-col: #102840;
	--background-col-alt: #102840;
	--background-highlight: #153959;
	--background-highlight-alt: #153959;
	--text-col: #ACCAE6;
	--highlight-col: #BDDFFF;
	--placeholder-col: #97B3CC;
	--link-col: #6DA1D8;
	--button-text-col: #608FBF;
	--outline-col: #608FBF;
	--rounding-big: 10px;
	--rounding-small: calc(var(--rounding-big) / 2);

	/* App Elements */
	--app-font: "Courier Prime Code";
	--app-bg: var(--background-col);
	--main-color: var(--background-col);
	--main-alt: var(--background-col-alt);
	--status-picker-color: var(--background-col);
	--sidebar-panel-color: var(--background-col-alt);
	--chat-color: var(--background-col);
	--tooltip-color: var(--background-col-alt);
	--tooltip-text-color: var(--text-col);
	--tooltip-shadow: var(--background-col-alt);

	/* Accent Elements */
	--accent-lightness: 100%;
	--accent-text-color: var(--background-col);

	/* Message Elements */
	--message-color: var(--background-col-alt);
	--message-color-hover: var(--background-highlight);
	--message-color-alt: var(--background-col-alt);
	--message-radius: var(--rounding-big);
	--media-radius: var(--rounding-big);
	--attachment-color: var(--background-col);
	--main-textarea-color: var(--background-col-alt);
	--main-textarea-color-alt: var(--background-col);
	--main-textarea-border: var(--outline-col);
	--main-textarea-radius: var(--rounding-big);

	/* Popout Menu Elements */
	--popout-color: var(--background-col-alt);
	--popout-color-alt: var(--background-col);
	--popout-header-border: var(--outline-col);
	--separator-color: var(--outline-col);
	--popout-radius: var(--rounding-big);
	--popout-radius-big: var(--rounding-big);

	/* Card Elements */
	--card-color-filled: var(--background-col-alt);
	--card-color-hover: var(--background-highlight-alt);
	--card-color-active: var(--background-col-alt);
	--card-color-alt: var(--background-col);
	--card-color-alt-hover: var(--background-hover);
	--card-border-color: var(--outline-col);
	--card-header-text-color: var(--text-col);
	--card-radius: var(--rounding-big);
	--card-radius-big: var(--rounding-big);

	/* Button Elements */
	--button-radius: var(--rounding-big);
	--button-link-text-color: var(--link-col);

	/* Slider And Switch Elements */
	--switch-knob-color: var(--button-text-col);
	--switch-slider-color: var(--background-col-alt);

	/* Input Elements */
	--input-color: var(--background-col-alt);
	--input-color-alt: var(--background-col);
	--input-border-color: var(--outline-col);
	--input-text-color: var(--text-col);
	--input-placeholder-color: var(--placeholder-col);

	/* Various Elements */
	--scrollbar-color: var(--button-text-col);
}

/* Fixes the bar above friend list(thanks CapnKitten(https://github.com/CapnKitten/Material-Discord/issues/233)) */
.container__9293f.themed__9293f {
	background-color: transparent;
	box-shadow: 0;
}

.children__9293f:after {
    display: none;
}
```

**Comment by CapnKitten** [comment]
What other things are you using to make it look like that?

**Comment by nnra6864** [comment]
> What other things are you using to make it look like that?

Equibop+link to your theme+quick css that I sent

**Comment by daki456** [comment]
+1
Same for Vesktop ^^

**Comment by dan0dev** [comment]
@nnra6864 
Not 100% sure what kind of CSS sorcery this is, but I fixed it by changing this:

```css
.vc-plainFolderIcon-plain .folderIconWrapper__48112 {
  background-color: color-mix(in oklab, var(--custom-folder-color, var(--bg-brand)) 40%, transparent);
}
```
to this:

```css
.vc-plainFolderIcon-plain .folderIconWrapper__48112 {
  background-color: color-mix(in oklab, var(--custom-folder-color, var(--bg-brand)) 40%, transparent);
}
}
```

Literally just added a closing bracket that somehow broke the syntax in a good way. If the author want to look into it, I guess this will be a starting point. I’m sure I’d find out why, but honestly… skimming through 19k+ lines of CSS is a bit much 😅

Attaching the file here, just drag n drop — folders should now be working. If anything else breaks, I’m afraid that’s out of my hands 

https://limewire.com/d/vcOVa#7wGGCOOLrD (hit the green download button)
