### ISSUE TITLE
Latest (theme?) update seems to have broken material you color theming

### ISSUE THREAD

**Issue by LuminarySage** [CapnKitten/Material-Discord#247]
I just restarted my discord not 10 minutes ago and my material discord theme has changed back to the default blue color from the green color I set

This is the quickcss snippet I've been using:
```css
:root {
    --accent-hue: 110;
    --accent-saturation: 90%;
    --accent-lightness: 60%;
    
    --accent-text-color: #fff;
}

.theme-dark {
    --saturation-modifier: 0.175;
    --lightness-modifier: 0.2;
    --text-lightness-modifier: 1.0;
}

.theme-light {
    --saturation-modifier: 0.175;
    --lightness-modifier: 2.02;
    --text-lightness-modifier: 1.0;
}
```

**System info:**
Windows 11 24H2
Discord stable 399648 (5301daf)
Vencord 8023b1b (Standalone)

**Comment by LuminarySage** [comment]
If I copy the accent color values to the theme section like below then weirdly the main pane isn't colored? It applies to dms, servers, etc. as well
```css
:root {
    --accent-hue: 110;
    --accent-saturation: 90%;
    --accent-lightness: 60%;
    
    --accent-text-color: #fff;
}

.theme-dark {
    --accent-hue: 110;
    --accent-saturation: 90%;
    --accent-lightness: 60%;

    --saturation-modifier: 0.175;
    --lightness-modifier: 0.2;
    --text-lightness-modifier: 1.0;
}

.theme-light {
    --accent-hue: 110;
    --accent-saturation: 90%;
    --accent-lightness: 60%;

    --saturation-modifier: 0.175;
    --lightness-modifier: 2.02;
    --text-lightness-modifier: 1.0;
}
```

![Image](https://github.com/user-attachments/assets/ba7f2e4f-ba42-4844-9671-f3d2d3795b1c)
