### ISSUE TITLE
Fix compatibility with PermissionsViewer

### ISSUE THREAD

**Issue by KaKi87** [CapnKitten/Material-Discord#46]
Hey,

Could you please add this somewhere please ?

```css
#permissions-modal-wrapper .modal-wrapper {
    z-index: 10000;
}
```

It's a fix for PermissionsViewer's modal showing behind the modal backdrop.

Thanks !
